# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        squared_thumbnail_medium:
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

    loaders:
        filesystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem

    #default loader to use for all filter sets
    data_loader: filesystem_loader

    resolvers:
        filesystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url: "/uploads"
                cache_prefix: media/cache

    cache: filesystem_resolver